### ISSUE TITLE
Incorrect relative URL somewhere

### ISSUE THREAD

**Issue by karger** [DmitrySharabin/mavo-firebase-firestore#16]
My app using the plugin is attempting to load  http://localhost/ifd/mavo-firebase-firestore.css .  Which suggests you're specifying a relative url somewhere you shouldn't.

**Comment by DmitrySharabin** [comment]
Are you including the plugin via `mv-plugins` or as a separate file? If as a separate file, unfortunately, you have to include accompanying CSS manually. I indeed use a relative path for this CSS-file, but only to make it work properly. Below is the quote from the plugin page on the Mavo site:

> Note that some plugins may also include CSS or other JavaScript files, which they expect to find in the same directory as the plugin’s main JS file. You do not have to worry about this if including the plugin via the `mv-plugins` attribute.

**Comment by DmitrySharabin** [comment]
Am going to close it since it's not an issue.
