### ISSUE TITLE
Without auth users cannot save to firebase

### ISSUE THREAD

**Issue by karger** [DmitrySharabin/mavo-firebase-firestore#18]
The plugin documentation says "if the authentication feature is on, only signed-in users can edit app's data, regardless of the security rules set for your app in the Firebase console. "  But if you create a firebase-plugin app without "auth", no save button is available in the mavo bar, so users cannot save at all.  It would sometimes be desirable to let non-signed-in users save.

Test case: click "Play" on the firebase todo app to get a new codepen, then remove "auth" from mv-firebase.

**Comment by DmitrySharabin** [comment]
Oh, yes. Previously this feature was enabled. But then I decided to disable it and unfortunately narrowed down the number of use cases. Re-enabled it. Thanks!
