### ISSUE TITLE
Defaults around no-auth and no-storage

### ISSUE THREAD

**Issue by karger** [DmitrySharabin/mavo-firebase-firestore#4]
I'm wondering about the role of these two attributes.  They seem to be inverting the complexity of different choices.  It would seem that the simplest uses of firebase would have neither auth nor storage, while more advanced uses would want one or the other or both.  Given the current design, it would seem I have to read the documentation to figure out why my simple app (where I didn't set up auth or storage) isn't working.    Wouldn't it be more straightforward to default to expecting neither, then throw an error if the author tries to use them without configuring them?

**Comment by DmitrySharabin** [comment]
Yes, that totally makes sense. I'll try to implement the logic you suggest.
Thank you very much for experimenting with the plugin and for your feedback.

**Comment by DmitrySharabin** [comment]
David, I released a new version of the plugin that supports the logic you suggested. Will you please give it a try and tell me whether the plugin now works the way you expect? The current logic is described [here](https://plugins.mavo.io/plugin/firebase-firestore#customization).

**Comment by DmitrySharabin** [comment]
I tested the new logic. For now, everything works as I expect it.
