### ISSUE TITLE
Google security warning

### ISSUE THREAD

**Issue by karger** [DmitrySharabin/mavo-firebase-firestore#5]
I'm working on a simple app using the plugin, and when I try to log in google gives me a scary warning.

![image](https://user-images.githubusercontent.com/1141086/82744324-f7443200-9d44-11ea-9848-6cfab24807c9.png)

Google seems to think that my app is seeking permission to manage all of a user's data in cloud storage, not just getting a username and password:

![image](https://user-images.githubusercontent.com/1141086/82744359-45593580-9d45-11ea-8aba-f0f9435c1b03.png)

**Comment by DmitrySharabin** [comment]
I think I know why you face this issue. I asked for extra permissions for future use: to be able to write security rules from an app. Removed it from the current version and moved it to a separate branch. Will you please check whether it fixed the problem?

**Comment by DmitrySharabin** [comment]
Since we don't have any new comments, assume the issue is fixed. :)
