### ISSUE TITLE
mv-path cannot handle multiple layers of nonexistent fields

### ISSUE THREAD

**Issue by karger** [DmitrySharabin/mavo-firebase-firestore#6]
If you specify mv-path="c" and c does not exist, it is created on save.  But if you specify mv-path="c/d" and c does not exist, then the relevant c and d nodes are not created and the save fails silently.  Test case here: http://people.csail.mit.edu/karger/Projects/Test/

**Comment by LeaVerou** [comment]
Are you sure this does not happen with other storage backends? If Dmitry is using the existing Mavo stuff `Mavo.Node#inPath` IIRC) for handling `mv-path`, a backend should not be able to break this.

**Comment by karger** [comment]
You're right, it fails with mv-storage="local" as well.

**Comment by DmitrySharabin** [comment]
Lea is right; I'm using the existing Mavo stuff.

So I believe I must close this issue since it's not relevant to the plugin itself, and I can't do anything with it.
