### ISSUE TITLE
authenticating multiple mavos on same page

### ISSUE THREAD

**Issue by karger** [DmitrySharabin/mavo-firebase-firestore#7]
If I create multiple firebase mavos on the same page and set mv-firebase="auth" on each, I have to log in to each mavo separately.  I guess this might be useful sometimes, but I suspect there are many cases where it would preferable to login once and have it work for all mavos on the page.

**Comment by DmitrySharabin** [comment]
I believe now it works as expected. If not, we can always re-open it.
